site_name: SQLite Viewer Documentation
nav:
  - Home: index.md
  - Modules:
    - Application: modules/app.md
    - Database Operations: modules/db_operations.md
    - AI Integration: modules/ai_integration.md
    - Configuration: modules/config.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_root_heading: false
            show_source: true

theme: readthedocs